= Replace With Alphabet Position | CodeWars Challenge
// :linkcss:
// :stylesheet: asciidoctor-original-with-overrides.css
// :stylesdir: {user-home}/Projects/proghowto
:webfonts:
:stem: latexmath
:icons!: font
:source-highlighter: pygments
:source-linenums-option:
:pygments-css: class
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:favicon: https://fernandobasso.dev/cmdline.png

https://www.codewars.com/kata/546f922b54af40e1e90001da/train/javascript

== Sample Of Expected Output
----
alphabetPosition('aBc XyZ');
// → 1 2 3 24 25 26

alphabetPosition('The sunset sets at twelve o\' clock.');
// → "20 8 5 19 21 14 19 5 20 19 5 20 19 1 20 20 23 5 12 22 5 15 3 12 15 3 11")

alphabetPosition('The narwhal bacons at midnight.');
// →  "20 8 5 14 1 18 23 8 1 12 2 1 3 15 14 19 1 20 13 9 4 14 9 7 8 20")
----

== JavaScript

COMPLAINT: How do I miss ranges in JavaScript like we have in Ruby, Haskell and other languages. Bash's beloved {a..z} is soooo missed here...


=== Solution 1

[source,javascript,lineos]
----
// makeAlphabet :: void -> string
// Creates an array with the lowercase alphabet.
function makeAlphabet() {
  const aCharCode = 'a'.charCodeAt(); // 97
  const zCharCode = 'z'.charCodeAt(); // 122

  const arr = [];
  for (let i = aCharCode; i <= zCharCode; ++i)
    arr.push(String.fromCharCode(i));

  return arr;
}

// alphabetPosition :: string -> string
// Produce string positions of letters from input string.
function alphabetPosition(s) {
  const alphabet = makeAlphabet();

  ////
  // Cleans the input string for non-alphabetic, a-z chars.
  const arr = s.toLowerCase().split('').filter(e => /[a-z]/.test(e));

  ////
  // Produces an array with the position of each char.
  // and joins the  array using spaces.
  return arr.reduce((acc, e) => {
    return [...acc, alphabet.indexOf(e) + 1];
  }, []).join(' ');
}
----


=== Solution 2

[source,javascript,lineos]
----
// alphabetPosition :: string -> string
// Produce string positions of letters from input string.
function alphabetPosition(s) {
  const aCharCode = 'a'.charCodeAt(); // 97

  ////
  // Produces an array with the position of each char.
  return s.toLowerCase()
    .match(/[a-z]/g)
    .map(n => n.charCodeAt() - 97 + 1)
    .join(' ');
}
----


`a` has char code 97. If we get the charcode of any letter in the alphabet, we can do:

    position_in_the_alphabet = letter_char_code - char_code_of_a

    a = 97
    b = 98
    a - a = 0
    a - b = 1

- `a` is at position 0
- `b` is at position 1


And we use `+ 1` to make `a` be at position 1, `b` at position 2, and so forth. The technique of using the decimal value of a character is demostrated in the K&R C book.


==== `filter' vs `match'

Instead of

    match(/[a-z]/g)

we could also have used

     .split('')
     .filter(e => /[a-z]/.test(e))

But then we would need both `filter` and `split`. `match' returns an array when the `g` flag is used, and therefore, no `split` is needed for this case.


++++
<style>
pre.pygments .tok-c1 {
  font-style: normal !important;
}
</style>
++++
