= Bash Arrays
:description: Examples and tips about using arrays in Bash.
// :linkcss:
// :stylesheet: myadoc.css
// :stylesdir: http://localhost:8000
// :stylesdir: {user-home}/Projects/proghowto
// :stem: latexmath
:webfonts!:
:icons: font
:source-highlighter: pygments
:source-linenums-option!:
:pygments-css: class
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:favicon: https://fernandobasso.dev/cmdline.png
:asterisk: *

== Introduction to Bash Arrays

=== Create and Use An Array

Create an array of numbers.
Use `()`, and, unlike in many other languages, separate elements with spaces, not commas:

[source,shell-session]
----
$ nums=(1 2 3 4)
----

Use the elements of the array in a loop:

[source,shell-session]
----
$ for n in "${nums[@]}" ; do printf '  %s\n' "Iteration $n" ; done
  Iteration 1
  Iteration 2
  Iteration 3
  Iteration 4
----

Get the length of the array:

[source,shell-session]
----
$ echo "${#nums[@]}"
4
----

Append elements to the array:

[source,shell-session]
----
$ nums+=(5 6)

$ echo "${#nums[@]}"
6

$ echo "${nums[@]}"
1 2 3 4 5 6
----

== Array Subscript asterisk * and at @

`man bash` (link:https://www.gnu.org/software/bash/manual/bash.html#Arrays[man bash on arrays^]):

[quote, attribution, cite title]
____
Any element of an array may be referenced using `${name[subscript]}``.
If the subscript is `@` or `{asterisk}`, the word expands to all members of the array name.
These subscripts differ only when the word appears within double quotes.
If the word is double-quoted, `${name[*]}`` expands to a single word with the value of each array member separated by the first character of the `IFS` variable, and `${name[@]}` expands each element of name to a separate word.
____

By default the value of `IFS` is ‘`{nbsp}\t\n`’, that is, a space, a tab, and a newline.
Let’s apply what we just discussed to convert an array to a string.

First, create an array with four letters, then, to see the difference between `[*]` and `[@]`, let’s use `printf '%s\n'`, since the specifier `%s` is reused as necessary to consume all given arguments:

[source,shell-session]
----
$ arr=(a b c d)

# <1>
$ printf '“%s”\n' "${arr[*]}"
“a b c d”

# <2>
$ printf '“%s”\n' "${arr[@]}"
“a”
“b”
“c”
“d”
----

<1> The array is expanded to a single element, thus `“%s”\n` is used only once, and the entire output is a single line inside the curly double quotes.

<2> Each element of the array is expanded to a separate word, thus causing `“%s”\n` to be used four times, producing the four output lines.
With `[*]` we can convert an array into a string.

Let's see what happens when we change the value of `IFS`:

[source,shell-session]
----
$ IFS='#'; printf '“%s”\n' "${nums[*]}"
“1#2#3#4”

$ IFS='_'; printf '“%s”\n' "${nums[*]}"
“1_2_3_4”

$ IFS=$'\t'; printf '“%s”\n' "${nums[*]}"
“1   2    3    4”

$ IFS=$'\n'; printf '“%s”\n' "${nums[*]}"
“1
2
3
4”
----


== Convert Array To String

We can get an array and turn it into a string with the elements separated by spaces. First, let's create an array of numbers:

[source,shell-session]
----
$ nums=(1 2 3 4)
----

Get the length of the array:

[source,shell-session]
----
$ echo "${#nums}"
4
----

Use the `[*]` syntax on the double-quoted name of the array to turn it into a string:

[source,shell-session]
----
$ strnums="${nums[*]}"
----

The resulting value now has length 7, because our string consists of four digits and three spaces.

[source,shell-session]
----
$ echo "${#strnums}"
7
----

Shows that it loops only once, printing the entire string in a single run:

[source,shell-session]
----
$ for x in "${strnums[@]}" ; do echo "“$x”" ; done
“1 2 3 4”
----

Now that `strnums` is a string, even using `[*]` to loop produces a single word:

[source,shell-session]
----
$ for x in "${strnums[*]}" ; do echo "“$x”" ; done
“1 2 3 4”
----

== read and IFS

[quote, help read]
--
Read a line from the standard input and split it into fields.

Reads a single line from the standard input, or from file descriptor FD if the -u option is supplied. The line is split into fields as with word splitting, and the first word is assigned to the first NAME, the second word to the second NAME, and so on, with any leftover words assigned to the last NAME. Only the characters found in $IFS are recognized as word delimiters.
--

One with the examples and explanations:

[source,shell-session]
----
# <1>
$ while IFS='|' read -r line ; do printf '%s\n' "$line" ; done <<<'a|b|c'
a|b|c

# <2>
$ while IFS='|' read -r -a line ; do printf '%s\n' "$line" ; done <<<'a|b|c'
a

# <3>
$ while IFS='|' read -r -a line ; do printf '%s\n' "${line[@]}" ; done <<<'a|b|c'
a
b
c

# <4>
$ while IFS='|' read -r -a line ; do printf '%s\n' "${line[*]}" ; done <<<'a|b|c'
a b c
----

<1> Since the `-a` option was not used for `read`, `IFS='|'` has no effect, and the entire input line is assigned as a single word to `line`.

<2> This time `-a` was used, but only one NAME was provided, therefore, all the words are “assigned to the last NAME”. However, since simply `"$line"` is used as the parameter to `printf`, it results in the first element of the array being retrieved (not all of them). It is similar to array pointers in C, where the name of the arrays is a pointer to the first element of the array.

<3> `-a` was used, and the `%s` format specifier is reused as many times as there are elements expanded in `${line[@]}`, therefore, we see three output lines.

<4> Because `"${line[*]}"` is used (instead of `"${line[@]}"`), the elements were expanded to a single word, and each element is separated by the first character of IFS, which is a space by default. This effectively joins the array elements into a single string, with spaces as the separator

`read` reads _a single line_ from the input source (`help read`). That is why this example does not loop twice and assign 'x', 'y', and 'z' in turn to `c`. Rather, it loops only once and assign the entire input to `c`.

[source,shell-session]
----
$ while IFS='|' read -r line ; do echo "$line" ; done <<<$'x|y|z'
x|y|z
----

TIP: Note we are quoting `|`, otherwise it would create a pipe and would not behave correctly. Remember that the two ways of quoting especial characters is by surrounding it with single quotes, or prepending it with a backslash.

Our input _is_ one single line, so, `read` reads that single line into `line`. IFS would split the input by “|” into an array if we told read to get that line, split it by the value of IFS, and then assign the words into an array.

[source,shell-session]
----
$ while read -r lang ; do echo "${lang}" ; done <<<$'Bash\nHaskell'
Bash
Haskell

$ while IFS='|' read -r -a arr ; do echo "${arr[@]}" ; done <<<$'Ba|sh\nHas|kell'
Ba sh
Has kell

$ while IFS='|' read -r -a arr ; do printf '%s\n' "${arr[@]}" ; done <<<$'Ba|sh\nHas|kell'
Ba
sh
Has
kell
----

<1> The input contains two lines.


== Links and Resources

* https://www.gnu.org/software/bash/manual/bash.html#Arrays[Bash Manual:
Arrays]
* https://www.gnu.org/software/bash/manual/bash.html#Special-Parameters[Bash
Manual: Special Parameters]
* https://www.gnu.org/software/bash/manual/bash.html#Word-Splitting[Bash
Manual: Word Splitting]
* https://unix.stackexchange.com/questions/26784/understanding-ifs[Unix StackExchange Question About IFS^]

++++
<script src="/highlight-navigation.js"></script>
++++
