= Bash Functions
:webfonts!:
:stem: latexmath
:icons!: font
:source-highlighter: pygments
:source-linenums-option:
:pygments-css: class
:sectlinks:
:toc: left
:sectnums!:
:toclevels: 6
:favicon: https://fernandobasso.dev/cmdline.png
:asterisk: *

[quote, bash manual]
Any element of an array may be referenced using ${name[subscript]}. The braces are required to avoid conflicts with the shell’s filename expansion operators. If the subscript is ‘@’ or ‘*’, the word expands to all members of the array name. These subscripts differ only when the word appears within double quotes. If the word is double-quoted, ${name[{asterisk}]} expands to a single word with the value of each array member separated by the first character of the IFS variable, and ${name[@]} expands each element of name to a separate word.

== exit vs return

`exit` can be used in scripts and in functions. In both cases, it causes _exiting_ from the script.

`return` can be used to exit a function. Both `exit` and `return` accept a number which acts as the exit status for the function or script.

[source,bash,lineos]
----
function greet () {
  printf '%s\n' 'Hello!' # <1>
}

greet # <2>

echo $? # <3>
----

1. The `greet` function prints a simple text. `printf` returns 0, meaning “success”, that is, “the printf command was executed successfully.”

2. Invoke the function greet. Because it does not provide an explicit return value, it returns the exit status of the last command.

3. `$?` contains the exit status of the last command, in this case, the return/exit status of the `greet` invocation.

=== exit inside a function

[source,bash,lineos]
----
function greet () {
  printf '%s\n' 'Hello'
  exit 1 # <1>
  echo 'world'
}

greet

echo 'The Force'
----

1. Prints “Hello”, exits with 1, and does not even print “world”. Even though `exit` was used inside the function, it exits from the entire script itself. That is why we never reach the line `echo 'The Force'` either.
